language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
before_install:
- openssl aes-256-cbc -K $encrypted_16d6b8e331d6_key -iv $encrypted_16d6b8e331d6_iv
  -in keystore.tar.gz.enc -out keystore.tar.gz -d
- tar -xvf keystore.tar.gz
script:
- "./gradlew clean build check"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_deploy:
- "./travisBeforeDeploy.sh"
deploy:
  provider: releases
  api_key:
    secure: cygHQJBTid+EAUjXuiT8ltJtl6anL/3EhUQX+1iCmDL4a1HA8q5BKDbFFKiNWQH1jMlny6f3M7wRIsTSIP97waQwYVRgRSLhuMxH3nC6wXj3GNETJVQ4x+QJwD82uCtNRNgy7acS86mHmgNPK7rKJWYPS6DOXOB8SNoaXYPd6b35LiIvgEX8rgNnTTVA6aYHKe6JQGQWU421GkzGWgP5mKKgS8POoaeNp64IGfYS5/Z7zeApKBGzS1ogiAxSvDoRXbWIRkaTX+lOeptXzSwj/eYaQ80W6oCtZG0VE0Ldl1EIHFMadSda0KctmVcfF/kv9MdareasSMloIp+7vu/HQJYuU8ZhzaI1qWD2cDoCvpIZVTb0GMes5bYgnT9RnE7ClTGAafVaR7Lr5pBgL//kQJH2tRg/MbFZt6K3NcfAvo+hJVegfxsQDLchrPLjl7EV+UfzcjJYbd+0G7dzAdtWaL8SMioEpa+02Vh8Qz81VUOwjLRotcpSb8oW7z1Sg6r6PVgzvmiRZJskqQZTyKZlb1Q0SB1X2pNBqJ6iMeumd6rrnnr7w5Onw0vehzj10vMYtpsbr0HAMvlW4eSMwLA+JuCNgNCJ/w1ViYk+5wNUd0KGkWpdHG/BKR1nq5KQIplXcHBFaTg7Yhit9RaHeR5vQZgbEN+xljuCQWsEyH6JcFg=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    branch: master
    repo: carlos-sancho-ramirez/android-java-langbook
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: ab0PnC3A6ZMXmXzQ6SvX9RVbMOos2Kj7JNmz8IyW9AEHsIdO4HXXGE6Oo8Q3zlJEjyZE51pzyvmDtBouHc1kn7VXC2IpIp7oCAW2Iz4FKZDgw3J+y4SfyosU90KD8gmkt7a37/3c6QUfYel6G4EU/I2vmjJFqMLGDhD07Z093QeceCiToBbwob84X35QaPypXDgjJMzLYuUWHooPzltqYX8pHoFWD/t1WT0n2TNGifKbATPDZcehHL9rq0GXzd7mRu7EM3Z3FvnHkiYMqD0DPUleY5HI03zEJoqk/cchqwasxtDnV+Vwk7Qmx4OMLsTLYNQxFwnnwYOBHKonn6TIg7HyfJgbFobmCpkTYPYpPVxHMDqlNka1CFEkMJEaBFAddncVmD1hhwFw/MUrE6uZovlmUUNNmb3YrM5s1IrZ5SHP49yf4fFzGW/u8ygkspR70GOMTX/Qf+3dhWxWDL38lFqebAKVXJnR2wcJThCeAHQ0TLe6GBf9NRhh/KJl1Zhu2NnPEvbwb3mWb7x4rTnI8vwjQSOcYSXQ+xj/YF6SYSVzl8NdqFV5lgt5iOnRRD287fI7rA3rc+OWFK1olLFtC9T9Fqg5FEWDN2xb2nSQ50ML12g7PTIKP8+ZdVXZ3JEWkXnKC4TIFS3q0mW/byIBexjegETt6wUkAPnPJZ/zBDw=
